app:
		@cd /home/sdn/Desktop/2/ik2220-assign-team9/application/ && sudo make app

topo:
		@cd /home/sdn/Desktop/2/ik2220-assign-team9/topology/ && sudo make topo

clean:
	sudo mn -c
	sudo pkill pox
	sudo killall click